FROM debian:10
MAINTAINER Daniel Schaefer <daniel.schaefer@hpe.com>

RUN apt-get update
RUN apt-get install -y autoconf automake autotools-dev build-essential bison flex
RUN apt-get install -y build-essential uuid-dev iasl git gcc nasm python3-distutils

RUN dpkg --add-architecture riscv64
RUN apt-get install -y gcc-riscv64-linux-gnu g++-riscv64-linux-gnu

RUN echo "/usr/local/lib/riscv64-linux-gnu" >> /etc/ld.so.conf.d/riscv64-linux-gnu.conf &&\
    echo "/lib/riscv64-linux-gnu" >> /etc/ld.so.conf.d/riscv64-linux-gnu.conf &&\
    echo "/usr/lib/riscv64-linux-gnu" >> /etc/ld.so.conf.d/riscv64-linux-gnu.conf &&\
    echo "/usr/riscv64-linux-gnu/lib/" >> /etc/ld.so.conf.d/riscv64-linux-gnu.conf

RUN ln -s /usr/riscv64-linux-gnu/lib/ld-linux-riscv64-lp64d.so.1 /lib

# To be compatible with old ubuntu if the toolchain is built for that
RUN ln -s /usr/lib/x86_64-linux-gnu/libmpfr.so.6 /usr/lib/x86_64-linux-gnu/libmpfr.so.4

# Alias python to python3 (EDK2 needs that)
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 10

# dtc is needed for platforms where DTC is embedded in earlier boot stages
RUN apt-get install device-tree-compiler
